export const cartItems = [
  {
    id: 1,
    img: "./milk.png",
    text: 'Pasteurized milk "House in the Village" 2.5%, 930 ml',
    isSea: true,
    is18: false,
    amount: 1,
    price: 7.99,
    fullPrice: 7.99,
  },
  {
    id: 2,
    img: "./sea.png",
    text: "Russian Sea trout fillet piece, lightly salted, 200g",
    isSea: true,
    is18: true,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
  },
  {
    id: 3,
    img: "./wine.png",
    text: "Wine Shiraz Mr Borio's, Simonsig, 2021",
    isSea: false,
    is18: true,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
  },
  {
    id: 4,
    img: "./milk.png",
    text: "Wine Shiraz Mr Borio's, Simonsig, 2021",
    isSea: false,
    is18: false,
    amount: 1,
    price: 7.99,
    fullPrice: 7.99,
    status: "warn",
  },
  {
    id: 5,
    img: "./milk.png",
    text: "Wine Shiraz Mr Borio's, Simonsig, 2021",
    isSea: false,
    is18: false,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
    status: "error",
    statusText: "Pasteurized milk 'House in the Village' 2.5%, 930 ml",
    statusTextStyle: true,
  },
  {
    id: 6,
    text: 'Pasteurized milk "House in the Village" 2.5%, 930 ml',
    isSea: true,
    is18: false,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
  },
  {
    id: 7,
    text: "Russian Sea trout fillet piece, lightly salted, 200g",
    isSea: true,
    is18: true,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
  },
  {
    id: 8,
    text: "Wine Shiraz Mr Borio's, Simonsig, 2021",
    isSea: false,
    is18: true,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
  },
  {
    id: 9,
    text: "Wine Shiraz Mr Borio's, Simonsig, 2021",
    isSea: false,
    is18: false,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
    status: "warn",
  },
  {
    id: 10,
    text: "Wine Shiraz Mr Borio's, Simonsig, 2021",
    isSea: false,
    is18: false,
    amount: 1,
    price: 7.99,
    discount: 10.99,
    fullPrice: 7.99,
    status: "error",
    statusText: "Pasteurized milk 'House in the Village' 2.5%, 930 ml",
    statusTextStyle: false,
  },
];
